#pragma once

#define ESP_PANEL_BOARD_DEFAULT_USE_CUSTOM  (1)

#if ESP_PANEL_BOARD_DEFAULT_USE_CUSTOM

#define ESP_PANEL_BOARD_NAME                "MimiClaw:ST77916-QSPI"
#define ESP_PANEL_BOARD_WIDTH               (360)
#define ESP_PANEL_BOARD_HEIGHT              (360)

#define ESP_PANEL_BOARD_USE_LCD             (1)

#if ESP_PANEL_BOARD_USE_LCD

#define ESP_PANEL_BOARD_LCD_CONTROLLER      ST77916
#define ESP_PANEL_BOARD_LCD_BUS_TYPE        (ESP_PANEL_BUS_TYPE_QSPI)
#define ESP_PANEL_BOARD_LCD_BUS_SKIP_INIT_HOST      (0)

#define ESP_PANEL_BOARD_LCD_QSPI_HOST_ID    (1)
#if !ESP_PANEL_BOARD_LCD_BUS_SKIP_INIT_HOST
#define ESP_PANEL_BOARD_LCD_QSPI_IO_SCK     (18)
#define ESP_PANEL_BOARD_LCD_QSPI_IO_DATA0   (46)
#define ESP_PANEL_BOARD_LCD_QSPI_IO_DATA1   (13)
#define ESP_PANEL_BOARD_LCD_QSPI_IO_DATA2   (11)
#define ESP_PANEL_BOARD_LCD_QSPI_IO_DATA3   (12)
#endif
#define ESP_PANEL_BOARD_LCD_QSPI_IO_CS      (14)
#define ESP_PANEL_BOARD_LCD_QSPI_MODE       (0)
#define ESP_PANEL_BOARD_LCD_QSPI_CLK_HZ     (40 * 1000 * 1000)
#define ESP_PANEL_BOARD_LCD_QSPI_CMD_BITS   (32)
#define ESP_PANEL_BOARD_LCD_QSPI_PARAM_BITS (8)

#define ESP_PANEL_BOARD_LCD_COLOR_BITS          (ESP_PANEL_LCD_COLOR_BITS_RGB565)
#define ESP_PANEL_BOARD_LCD_COLOR_BGR_ORDER     (0)
#define ESP_PANEL_BOARD_LCD_COLOR_INEVRT_BIT    (0)

#define ESP_PANEL_BOARD_LCD_SWAP_XY             (0)
#define ESP_PANEL_BOARD_LCD_MIRROR_X            (0)
#define ESP_PANEL_BOARD_LCD_MIRROR_Y            (0)
#define ESP_PANEL_BOARD_LCD_GAP_X               (0)
#define ESP_PANEL_BOARD_LCD_GAP_Y               (0)

#ifndef MIMI_LCD_RST_GPIO
#define MIMI_LCD_RST_GPIO                       (3)
#endif

#define ESP_PANEL_BOARD_LCD_RST_IO              (MIMI_LCD_RST_GPIO)
#define ESP_PANEL_BOARD_LCD_RST_LEVEL           (0)

#endif

#define ESP_PANEL_BOARD_USE_TOUCH               (0)

#define ESP_PANEL_BOARD_USE_BACKLIGHT           (1)

#if ESP_PANEL_BOARD_USE_BACKLIGHT
#define ESP_PANEL_BOARD_BACKLIGHT_TYPE          (ESP_PANEL_BACKLIGHT_TYPE_SWITCH_GPIO)
#define ESP_PANEL_BOARD_BACKLIGHT_IO            (44)
#define ESP_PANEL_BOARD_BACKLIGHT_ON_LEVEL      (1)
#define ESP_PANEL_BOARD_BACKLIGHT_IDLE_OFF      (0)
#endif

#endif

#define ESP_PANEL_BOARD_CUSTOM_FILE_VERSION_MAJOR 1
#define ESP_PANEL_BOARD_CUSTOM_FILE_VERSION_MINOR 2
#define ESP_PANEL_BOARD_CUSTOM_FILE_VERSION_PATCH 0
